INSERT INTO plazos_fijos (tipo, tna, banco, fecha_de_registro)
	 VALUES ('T', 133, 'BANCO-DE-LA-NACION-ARGENTINA', current_timestamp),
			('T', 133, 'BANCO-SANTANDER-ARGENTINA-S.A.', current_timestamp),
			('T', 133, 'BANCO-DE-GALICIA-Y-BUENOS-AIRES-S.A.U.', current_timestamp),
			('T', 133, 'BANCO-DE-LA-PROVINCIA-DE-BUENOS-AIRES', current_timestamp),
			('T', 133, 'BANCO-BBVA-ARGENTINA-S.A.', current_timestamp),
			('T', 133, 'BANCO-MACRO-S.A.', current_timestamp),
			('T', 133, 'HSBC-BANK-ARGENTINA-S.A.', current_timestamp),
			('T', 133, 'BANCO-CREDICOOP-COOPERATIVO-LIMITADO', current_timestamp),
			('T', 133, 'INDUSTRIAL-AND-COMMERCIAL-BANK-OF-CHINA-(ARGENTINA)-S.A.U.', current_timestamp),
			('T', 133, 'BANCO-DE-LA-CIUDAD-DE-BUENOS-AIRES', current_timestamp),
			('T', 133, 'BANCO-BICA-S.A.', current_timestamp),
			('T', 133, 'BANCO-CMF-S.A.', current_timestamp),
			('T', 133, 'BANCO-COMAFI-SOCIEDAD-ANONIMA', current_timestamp),
			('T', 133, 'BANCO-DE-CORRIENTES-S.A.', current_timestamp),
			('T', 133, 'BANCO-DE-LA-PROVINCIA-DE-CORDOBA-S.A.', current_timestamp),
			('T', 133, 'BANCO-DEL-CHUBUT-S.A.', current_timestamp),
			('T', 133, 'BANCO-DEL-SOL-S.A.', current_timestamp),
			('T', 133, 'BANCO-DINO-S.A.', current_timestamp),
			('T', 133, 'BANCO-HIPOTECARIO-S.A.', current_timestamp),
			('T', 111, 'BANCO-JULIO-SOCIEDAD-ANONIMA', current_timestamp),
			('T', 116.5, 'BANCO-MASVENTAS-S.A.', current_timestamp),
			('T', 133, 'BANCO-MERIDIAN-S.A.', current_timestamp),
			('T', 127, 'BANCO-PROVINCIA-DE-TIERRA-DEL-FUEGO', current_timestamp),
			('T', 133, 'BANCO-VOII-S.A.', current_timestamp),
			('T', 133, 'BIBANK-S.A.', current_timestamp),
			('T', 133, 'CREDITO-REGIONAL-COMPAÑIA-FINANCIERA-S.A.', current_timestamp);